site_name: Maritime Robotics Landscape
site_url: https://ros-maritime.oceansoft.org/
theme: readthedocs

copyright: 'Information assembled by the ROS Maritime Robotics Working Group. Privacy-respecting analytics with GoatCounter.'

nav:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- FAQ: 'faq.md'
- Glossary: 'glossary.md'
- Vehicle Types: 'vehicle_types.md'
- Autonomy Stacks: 'autonomy_stacks.md'
- Simulation: 'simulation.md'
- Hardware: 'hardware.md'
- Software: 'software.md'
- Drivers: 'drivers.md'
- Datasets: 'datasets.md'
- Education & Tutorials: 'education_and_tutorials.md'
- Events: 'events.md'
- Expert Reference: 'expert_reference.md'
- Operations: 'operations.md'
- Integration Examples: 'integration_examples.md'

markdown_extensions:
- pymdownx.snippets:
    check_paths: true
- admonition

plugins:
    - search
    - git-revision-date-localized:
        fallback_to_build_date: true
    - include-markdown
